import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Main = () => {
  return (
    <div>
      <h1>왁뚜</h1>
    </div>
  )
}

export default Main